site_name: GEOBOX.IO
theme: cosmo
pages:
    - Introduction: 'index.md'
    - Getting Started: 'GettingStarted.md'
    - Events: 'GeoBoxEvents.md'
    - GeoFences: 'GeoFences.md'
copyright: Â© 2016 Locwise Technologies. All rights reserved.
